export const GET_DOGS = 'GET_DOGS'
export const GET_DOG_NAME = 'GET_DOG_NAME';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
export const RESET = 'RESET'
export const ADD_DOG = 'ADD_DOG'
export const GET_DOG_ID = 'GET_DOG_ID'
export const CLEAR_DETAIL = 'CLEAR DETAIL'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const FILTER_SORT = 'FILTER_SORT'